language: python
python: '2.7'
sudo: required
dist: trusty
env:
  global:
  - TOX_ENV=py27
  - SITE_URL="https://drosofff.github.io/docs/"
  - GH_USER_NAME="Christophe Antoniewski"
  - GH_USER_EMAIL="drosofff@gmail.com"
  - GH_REF="github.com/drosofff/docs.git"
  - secure: II51TBzYAHN8Nr6RhrWPKqGkDPeBl1Dfqzqp+aOdpPB9RPiCjsjgEpBjf61RkWuBOwLjKeOJUgfacGWVtACfLvjNQAkNbcLPhpWxK7aSgADlRqY0SIOEeWA0+/VofCGEHyDPnpC7F9mjRDzYnmUtoeN1oTXHD/N8p3/MYsUO+zcwipGTZQpU8ZUsQM3qZ9wy/Kn/1S343gfrsXBAEZBYrEJ36a6S4j5IPtFfQLK9sdhwiP2EwO3r5eLlDci2yKIf7qHQqyvr3A8e/JNv8aLI10gWlmysrQHbhRN8g62ecgJTibYwTgDuXed6S19w6PGhVlpLczcwczSA18PpTXeIG1uxC8GlzPdGVDsljEC+uIm5a8hLFV/bj/OtQ/vkqCeQG1Bm3HEv3fdv5IDiwwF3u4K0xMBtNToF8d39DXn5k6X+NzVCBNOXCHwt8QfjuXXoyqVxFJhciyeIFHJAr6mmAPQvV4opAPv5iETFKNHL2nQClyH1IIr2gKR0XKP6ZqK6igp+41w9uhm/rWct3DXCUqSAtEk12Ksbenbr2aibxzAzjLEdIzpo+t67I3l7mS+T/sk4lwj2J3ZQ0MF7DFHeeS5FYiOJVw8PXOxkxgX+KP+uY1m3Vw8PrcS/bUpM32+C2/3OOhN673matPlWWpwQ+8PNR0ki5FfYQVd5g1cGTc4=
install: true
script:
- bash ./deploy.sh
